using Content.Client.UserInterface.Controls;
using Content.Shared._Pinwheel.AlienRock;
using Content.Shared._Pinwheel.AlienRock.Equipment;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Pinwheel.AlienRock.Ui;

[GenerateTypedNameReferences]
public sealed partial class AlienScannerDisplay : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IGameTiming _timing= default!;

    private EntityUid _owner;
    private TimeSpan? _updateNext;
    private TimeSpan _updateRate;
    private List<string> _nodeNames = new();

    public AlienScannerDisplay()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
    }

    public void SetOwner(EntityUid uid)
    {
        if (!_ent.TryGetComponent<AlienScannerComponent>(uid, out var comp))
            return;

        _updateRate = comp.UiUpdateRate;
        _owner = uid;
    }

    /// <inheritdoc />
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_updateNext != null
            && _updateNext > _timing.CurTime)
            return;

        _updateNext = _timing.CurTime + _updateRate;

        if (!_ent.TryGetComponent<AlienScannerConnectedComponent>(_owner, out var con))
        { // set text with empty node list if we're not connected
            var empty = new List<string>();
            SetText(false, empty);
            return;
        }

        if (!_ent.TryGetComponent<AlienRockComponent>(con.Attached, out var rock))
            throw new Exception("Entity attached to alien scanner is not an artifact.");

        if (rock.Nodes is null)
            throw new Exception("Artifact does not have a node container");

        _nodeNames.Clear();

        var nodeList = rock.Nodes.ContainedEntities;

        foreach (var uid in nodeList)
        {
            var node = _ent.GetNetEntity(uid);
            _ent.TryGetEntityData(node, out var _, out var nodeMeta);
            _nodeNames.Add(nodeMeta!.EntityName);
        }

        SetText(true, _nodeNames);
    }

    /// <summary>
    /// Updates labels with scanned artifact data and list of triggered nodes from component.
    /// </summary>
    private void SetText(
        bool connected,
        List<string> nodes)
    {
        NodeScannerState.Text = connected
            ? Loc.GetString("node-scanner-artifact-connected")
            : Loc.GetString("node-scanner-artifact-non-connected");

        ActiveNodesList.Children.Clear();

        if (nodes.Count > 0)
        {
            // show list of triggered nodes instead of 'no data' placeholder
            NoActiveNodeDataLabel.Visible = false;
            ActiveNodesList.Visible = true;

            foreach (var node in nodes)
            {
                var nodeLabel = new Button
                {
                    Text = node,
                    Margin = new Thickness(15, 5, 0, 0),
                    MaxHeight = 40,
                    Disabled = true
                };
                ActiveNodesList.Children.Add(nodeLabel);
            }
        }
        else
        {
            // clear list of activated nodes (done previously), show 'no data' placeholder
            NoActiveNodeDataLabel.Visible = true;
            ActiveNodesList.Visible = false;
        }
    }
}
