using System.Text;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Client._Pinwheel.AlienRock;
using Content.Shared._Pinwheel.AlienRock;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Pinwheel.AlienRock.Ui;

[GenerateTypedNameReferences]
public sealed partial class AlienRockConsoleMenu : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;

    private readonly AlienRockDestroyerSystem _destroyer;
    private readonly MetaDataSystem _meta = default!;

    private Entity<AlienRockConsoleComponent> _owner;

    public event Action? OnDestroyButtonPressed;

    public AlienRockConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _destroyer = _ent.System<AlienRockDestroyerSystem>();
        _meta = _ent.System<MetaDataSystem>();

        DestroyButton.OnPressed += StartDestroy;
    }

    public void SetOwner(EntityUid owner)
    {
        if (!_ent.TryGetComponent<AlienRockConsoleComponent>(owner, out var comp))
        {
            Close();
            return;
        }

        _owner = (owner, comp);
        Update(_owner);
    }

    private void StartDestroy(BaseButton.ButtonEventArgs obj)
    {
        if (!_destroyer.TryGetArtifactFromConsole(_owner, out var artifact))
            return;

        OnDestroyButtonPressed?.Invoke();
    }

    public void Update(Entity<AlienRockConsoleComponent> ent)
    {
        _destroyer.TryGetArtifactFromConsole(ent, out var arti);

        ArtifactView.SetEntity(arti);
        DestroyButton.Disabled = arti == null;

        if (!_destroyer.TryGetDestroyer(ent, out _))
            ArtifactLabel.Text = Loc.GetString("alienrock-console-info-no-destroyer");
        else if (arti == null)
            ArtifactLabel.Text = Loc.GetString("alienrock-console-info-no-artifact");
        else
            ArtifactLabel.Text = Loc.GetString("alienrock-console-info-ready");
    }
}
