using Content.Client.UserInterface.Controls;
using Content.Shared._Pinwheel.AlienRock;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Pinwheel.AlienRock.Ui;

[GenerateTypedNameReferences]
public sealed partial class AlienRockScanner : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IGameTiming _timing= default!;

    private TimeSpan? _nextUpdate;
    private EntityUid _owner;
    private TimeSpan _updateTime;

    public AlienRockScanner()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Sets entity that represents hand-held xeno artifact node scanner for which window is opened.
    /// Closes window if <see cref="NodeScannerComponent"/> is not present on entity.
    /// </summary>
    public void SetOwner(EntityUid uid)
    {
        if (!_ent.TryGetComponent<AlienRockScannerComponent>(uid, out var comp))
        {
            Close();
            return;
        }

        _updateTime = comp.UiUpdateRate;
        _owner = uid;
    }

    /// <inheritdoc />
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

/*
        if(_nextUpdate  != null && _timing.CurTime < _nextUpdate)
            return;

        _nextUpdate = _timing.CurTime + _updateFromAttachedFrequency;

        if (!_ent.TryGetComponent(_owner, out NodeScannerConnectedComponent? connectedScanner))
        {
            Update(false, ArtifactState.None);
            return;
        }

        var attachedArtifactEnt = connectedScanner.AttachedTo;
        if (!_ent.TryGetComponent(attachedArtifactEnt, out XenoArtifactComponent? artifactComponent))
            return;

        _ent.TryGetComponent(attachedArtifactEnt, out XenoArtifactUnlockingComponent? unlockingComponent);

        _triggeredNodeNames.Clear();
        ArtifactState artifactState;
        if (unlockingComponent == null)
        {
            var timeToUnlockAvailable = artifactComponent.NextUnlockTime - _timing.CurTime;
            artifactState = timeToUnlockAvailable > TimeSpan.Zero
                ? ArtifactState.Cooldown
                : ArtifactState.Ready;
        }
        else
        {
            var triggeredIndexes = unlockingComponent.TriggeredNodeIndexes;

            foreach (var triggeredIndex in triggeredIndexes)
            {
                var node = _artifact.GetNode((attachedArtifactEnt, artifactComponent), triggeredIndex);
                var triggeredNodeName = (_ent.GetComponentOrNull<NameIdentifierComponent>(node)?.Identifier ?? 0).ToString("D3");
                _triggeredNodeNames.Add(triggeredNodeName);
            }

            artifactState = ArtifactState.Unlocking;
        }

        Update(true, artifactState, _triggeredNodeNames);
        */
    }

    /// <summary>
    /// Updates labels with scanned artifact data and list of triggered nodes from component.
    /// </summary>
    private void Update(bool isConnected)
    {
        ArtifactStateLabel.Text = "Sample text";
        NodeScannerState.Text = isConnected
            ? Loc.GetString("node-scanner-artifact-connected")
            : Loc.GetString("node-scanner-artifact-non-connected");

        ActiveNodesList.Children.Clear();

        /*if (triggeredNodeNames.Count > 0)
        {
            // show list of triggered nodes instead of 'no data' placeholder
            NoActiveNodeDataLabel.Visible = false;
            ActiveNodesList.Visible = true;

            foreach (var nodeId in triggeredNodeNames)
            {
                var nodeLabel = new Button
                {
                    Text = nodeId,
                    Margin = new Thickness(15, 5, 0, 0),
                    MaxHeight = 40,
                    Disabled = true
                };
                ActiveNodesList.Children.Add(nodeLabel);
            }
        }
        else
        {
            // clear list of activated nodes (done previously), show 'no data' placeholder
            NoActiveNodeDataLabel.Visible = true;
            ActiveNodesList.Visible = false;
        }*/
    }
}
